# Generated by Django 2.1.3 on 2018-11-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='insructions',
            new_name='instructions',
        ),
    ]
